### ISSUE TITLE
IAM Policy for Cloudfront Invalidation Incorrect

### ISSUE THREAD

**Issue by jlev** [colab-coop/action-page#14]
I'm having trouble with the default IAM permissions in `aws/iam-permissions.json`, and am getting this error. 

```
/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Could not invalidate cloudfront: AccessDenied: User: arn:aws:iam::664240040147:user/buytwitter is not authorized to perform: cloudfront:CreateInvalidation
    at Request.callListeners (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jlev/Code/WeAreTwitter/buytwitter/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

It looks like IAM users on Cloudfront can't specify resource level permissions (https://forums.aws.amazon.com/thread.jspa?threadID=244541), so we have to grant the ability to invalidate to all files.

Does that open security concerns?

**Comment by eethann** [comment]
Thanks @jlev, I'll take a closer look and loop back.
